/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/custom/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDbRoles implements DbRoleInterface
type FakeDbRoles struct {
	Fake *FakeCustomV1alpha1
	ns   string
}

var dbrolesResource = schema.GroupVersionResource{Group: "custom.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "dbroles"}

var dbrolesKind = schema.GroupVersionKind{Group: "custom.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "DbRole"}

// Get takes name of the dbRole, and returns the corresponding dbRole object, and an error if there is any.
func (c *FakeDbRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dbrolesResource, c.ns, name), &v1alpha1.DbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DbRole), err
}

// List takes label and field selectors, and returns the list of DbRoles that match those selectors.
func (c *FakeDbRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DbRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dbrolesResource, dbrolesKind, c.ns, opts), &v1alpha1.DbRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DbRoleList{ListMeta: obj.(*v1alpha1.DbRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.DbRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dbRoles.
func (c *FakeDbRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dbrolesResource, c.ns, opts))

}

// Create takes the representation of a dbRole and creates it.  Returns the server's representation of the dbRole, and an error, if there is any.
func (c *FakeDbRoles) Create(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.CreateOptions) (result *v1alpha1.DbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dbrolesResource, c.ns, dbRole), &v1alpha1.DbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DbRole), err
}

// Update takes the representation of a dbRole and updates it. Returns the server's representation of the dbRole, and an error, if there is any.
func (c *FakeDbRoles) Update(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.UpdateOptions) (result *v1alpha1.DbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dbrolesResource, c.ns, dbRole), &v1alpha1.DbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DbRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDbRoles) UpdateStatus(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.UpdateOptions) (*v1alpha1.DbRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dbrolesResource, "status", c.ns, dbRole), &v1alpha1.DbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DbRole), err
}

// Delete takes name of the dbRole and deletes it. Returns an error if one occurs.
func (c *FakeDbRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dbrolesResource, c.ns, name), &v1alpha1.DbRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDbRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dbrolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DbRoleList{})
	return err
}

// Patch applies the patch and returns the patched dbRole.
func (c *FakeDbRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DbRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dbrolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DbRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DbRole), err
}
