/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/custom/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDnsConfigurationClusterAwses implements DnsConfigurationClusterAwsInterface
type FakeDnsConfigurationClusterAwses struct {
	Fake *FakeCustomV1alpha1
	ns   string
}

var dnsconfigurationclusterawsesResource = schema.GroupVersionResource{Group: "custom.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "dnsconfigurationclusterawses"}

var dnsconfigurationclusterawsesKind = schema.GroupVersionKind{Group: "custom.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "DnsConfigurationClusterAws"}

// Get takes name of the dnsConfigurationClusterAws, and returns the corresponding dnsConfigurationClusterAws object, and an error if there is any.
func (c *FakeDnsConfigurationClusterAwses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DnsConfigurationClusterAws, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnsconfigurationclusterawsesResource, c.ns, name), &v1alpha1.DnsConfigurationClusterAws{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DnsConfigurationClusterAws), err
}

// List takes label and field selectors, and returns the list of DnsConfigurationClusterAwses that match those selectors.
func (c *FakeDnsConfigurationClusterAwses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DnsConfigurationClusterAwsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnsconfigurationclusterawsesResource, dnsconfigurationclusterawsesKind, c.ns, opts), &v1alpha1.DnsConfigurationClusterAwsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DnsConfigurationClusterAwsList{ListMeta: obj.(*v1alpha1.DnsConfigurationClusterAwsList).ListMeta}
	for _, item := range obj.(*v1alpha1.DnsConfigurationClusterAwsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dnsConfigurationClusterAwses.
func (c *FakeDnsConfigurationClusterAwses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnsconfigurationclusterawsesResource, c.ns, opts))

}

// Create takes the representation of a dnsConfigurationClusterAws and creates it.  Returns the server's representation of the dnsConfigurationClusterAws, and an error, if there is any.
func (c *FakeDnsConfigurationClusterAwses) Create(ctx context.Context, dnsConfigurationClusterAws *v1alpha1.DnsConfigurationClusterAws, opts v1.CreateOptions) (result *v1alpha1.DnsConfigurationClusterAws, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnsconfigurationclusterawsesResource, c.ns, dnsConfigurationClusterAws), &v1alpha1.DnsConfigurationClusterAws{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DnsConfigurationClusterAws), err
}

// Update takes the representation of a dnsConfigurationClusterAws and updates it. Returns the server's representation of the dnsConfigurationClusterAws, and an error, if there is any.
func (c *FakeDnsConfigurationClusterAwses) Update(ctx context.Context, dnsConfigurationClusterAws *v1alpha1.DnsConfigurationClusterAws, opts v1.UpdateOptions) (result *v1alpha1.DnsConfigurationClusterAws, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnsconfigurationclusterawsesResource, c.ns, dnsConfigurationClusterAws), &v1alpha1.DnsConfigurationClusterAws{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DnsConfigurationClusterAws), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDnsConfigurationClusterAwses) UpdateStatus(ctx context.Context, dnsConfigurationClusterAws *v1alpha1.DnsConfigurationClusterAws, opts v1.UpdateOptions) (*v1alpha1.DnsConfigurationClusterAws, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dnsconfigurationclusterawsesResource, "status", c.ns, dnsConfigurationClusterAws), &v1alpha1.DnsConfigurationClusterAws{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DnsConfigurationClusterAws), err
}

// Delete takes name of the dnsConfigurationClusterAws and deletes it. Returns an error if one occurs.
func (c *FakeDnsConfigurationClusterAwses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dnsconfigurationclusterawsesResource, c.ns, name), &v1alpha1.DnsConfigurationClusterAws{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDnsConfigurationClusterAwses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnsconfigurationclusterawsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DnsConfigurationClusterAwsList{})
	return err
}

// Patch applies the patch and returns the patched dnsConfigurationClusterAws.
func (c *FakeDnsConfigurationClusterAwses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DnsConfigurationClusterAws, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnsconfigurationclusterawsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DnsConfigurationClusterAws{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DnsConfigurationClusterAws), err
}
