/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BackupScheduleListerExpansion allows custom methods to be added to
// BackupScheduleLister.
type BackupScheduleListerExpansion interface{}

// BackupScheduleNamespaceListerExpansion allows custom methods to be added to
// BackupScheduleNamespaceLister.
type BackupScheduleNamespaceListerExpansion interface{}

// ProviderAccessListerExpansion allows custom methods to be added to
// ProviderAccessLister.
type ProviderAccessListerExpansion interface{}

// ProviderAccessNamespaceListerExpansion allows custom methods to be added to
// ProviderAccessNamespaceLister.
type ProviderAccessNamespaceListerExpansion interface{}

// ProviderAccessAuthorizationListerExpansion allows custom methods to be added to
// ProviderAccessAuthorizationLister.
type ProviderAccessAuthorizationListerExpansion interface{}

// ProviderAccessAuthorizationNamespaceListerExpansion allows custom methods to be added to
// ProviderAccessAuthorizationNamespaceLister.
type ProviderAccessAuthorizationNamespaceListerExpansion interface{}

// ProviderAccessSetupListerExpansion allows custom methods to be added to
// ProviderAccessSetupLister.
type ProviderAccessSetupListerExpansion interface{}

// ProviderAccessSetupNamespaceListerExpansion allows custom methods to be added to
// ProviderAccessSetupNamespaceLister.
type ProviderAccessSetupNamespaceListerExpansion interface{}

// ProviderSnapshotListerExpansion allows custom methods to be added to
// ProviderSnapshotLister.
type ProviderSnapshotListerExpansion interface{}

// ProviderSnapshotNamespaceListerExpansion allows custom methods to be added to
// ProviderSnapshotNamespaceLister.
type ProviderSnapshotNamespaceListerExpansion interface{}

// ProviderSnapshotBackupPolicyListerExpansion allows custom methods to be added to
// ProviderSnapshotBackupPolicyLister.
type ProviderSnapshotBackupPolicyListerExpansion interface{}

// ProviderSnapshotBackupPolicyNamespaceListerExpansion allows custom methods to be added to
// ProviderSnapshotBackupPolicyNamespaceLister.
type ProviderSnapshotBackupPolicyNamespaceListerExpansion interface{}

// ProviderSnapshotRestoreJobListerExpansion allows custom methods to be added to
// ProviderSnapshotRestoreJobLister.
type ProviderSnapshotRestoreJobListerExpansion interface{}

// ProviderSnapshotRestoreJobNamespaceListerExpansion allows custom methods to be added to
// ProviderSnapshotRestoreJobNamespaceLister.
type ProviderSnapshotRestoreJobNamespaceListerExpansion interface{}
