/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/ldap/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVerifies implements VerifyInterface
type FakeVerifies struct {
	Fake *FakeLdapV1alpha1
	ns   string
}

var verifiesResource = schema.GroupVersionResource{Group: "ldap.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "verifies"}

var verifiesKind = schema.GroupVersionKind{Group: "ldap.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "Verify"}

// Get takes name of the verify, and returns the corresponding verify object, and an error if there is any.
func (c *FakeVerifies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Verify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(verifiesResource, c.ns, name), &v1alpha1.Verify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Verify), err
}

// List takes label and field selectors, and returns the list of Verifies that match those selectors.
func (c *FakeVerifies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VerifyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(verifiesResource, verifiesKind, c.ns, opts), &v1alpha1.VerifyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VerifyList{ListMeta: obj.(*v1alpha1.VerifyList).ListMeta}
	for _, item := range obj.(*v1alpha1.VerifyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested verifies.
func (c *FakeVerifies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(verifiesResource, c.ns, opts))

}

// Create takes the representation of a verify and creates it.  Returns the server's representation of the verify, and an error, if there is any.
func (c *FakeVerifies) Create(ctx context.Context, verify *v1alpha1.Verify, opts v1.CreateOptions) (result *v1alpha1.Verify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(verifiesResource, c.ns, verify), &v1alpha1.Verify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Verify), err
}

// Update takes the representation of a verify and updates it. Returns the server's representation of the verify, and an error, if there is any.
func (c *FakeVerifies) Update(ctx context.Context, verify *v1alpha1.Verify, opts v1.UpdateOptions) (result *v1alpha1.Verify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(verifiesResource, c.ns, verify), &v1alpha1.Verify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Verify), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVerifies) UpdateStatus(ctx context.Context, verify *v1alpha1.Verify, opts v1.UpdateOptions) (*v1alpha1.Verify, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(verifiesResource, "status", c.ns, verify), &v1alpha1.Verify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Verify), err
}

// Delete takes name of the verify and deletes it. Returns an error if one occurs.
func (c *FakeVerifies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(verifiesResource, c.ns, name), &v1alpha1.Verify{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVerifies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(verifiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VerifyList{})
	return err
}

// Patch applies the patch and returns the patched verify.
func (c *FakeVerifies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Verify, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(verifiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Verify{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Verify), err
}
