/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/privatelink/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEndpointServiceAdls implements EndpointServiceAdlInterface
type FakeEndpointServiceAdls struct {
	Fake *FakePrivatelinkV1alpha1
	ns   string
}

var endpointserviceadlsResource = schema.GroupVersionResource{Group: "privatelink.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "endpointserviceadls"}

var endpointserviceadlsKind = schema.GroupVersionKind{Group: "privatelink.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "EndpointServiceAdl"}

// Get takes name of the endpointServiceAdl, and returns the corresponding endpointServiceAdl object, and an error if there is any.
func (c *FakeEndpointServiceAdls) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EndpointServiceAdl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(endpointserviceadlsResource, c.ns, name), &v1alpha1.EndpointServiceAdl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointServiceAdl), err
}

// List takes label and field selectors, and returns the list of EndpointServiceAdls that match those selectors.
func (c *FakeEndpointServiceAdls) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EndpointServiceAdlList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(endpointserviceadlsResource, endpointserviceadlsKind, c.ns, opts), &v1alpha1.EndpointServiceAdlList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EndpointServiceAdlList{ListMeta: obj.(*v1alpha1.EndpointServiceAdlList).ListMeta}
	for _, item := range obj.(*v1alpha1.EndpointServiceAdlList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested endpointServiceAdls.
func (c *FakeEndpointServiceAdls) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(endpointserviceadlsResource, c.ns, opts))

}

// Create takes the representation of a endpointServiceAdl and creates it.  Returns the server's representation of the endpointServiceAdl, and an error, if there is any.
func (c *FakeEndpointServiceAdls) Create(ctx context.Context, endpointServiceAdl *v1alpha1.EndpointServiceAdl, opts v1.CreateOptions) (result *v1alpha1.EndpointServiceAdl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(endpointserviceadlsResource, c.ns, endpointServiceAdl), &v1alpha1.EndpointServiceAdl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointServiceAdl), err
}

// Update takes the representation of a endpointServiceAdl and updates it. Returns the server's representation of the endpointServiceAdl, and an error, if there is any.
func (c *FakeEndpointServiceAdls) Update(ctx context.Context, endpointServiceAdl *v1alpha1.EndpointServiceAdl, opts v1.UpdateOptions) (result *v1alpha1.EndpointServiceAdl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(endpointserviceadlsResource, c.ns, endpointServiceAdl), &v1alpha1.EndpointServiceAdl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointServiceAdl), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEndpointServiceAdls) UpdateStatus(ctx context.Context, endpointServiceAdl *v1alpha1.EndpointServiceAdl, opts v1.UpdateOptions) (*v1alpha1.EndpointServiceAdl, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(endpointserviceadlsResource, "status", c.ns, endpointServiceAdl), &v1alpha1.EndpointServiceAdl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointServiceAdl), err
}

// Delete takes name of the endpointServiceAdl and deletes it. Returns an error if one occurs.
func (c *FakeEndpointServiceAdls) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(endpointserviceadlsResource, c.ns, name), &v1alpha1.EndpointServiceAdl{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEndpointServiceAdls) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(endpointserviceadlsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EndpointServiceAdlList{})
	return err
}

// Patch applies the patch and returns the patched endpointServiceAdl.
func (c *FakeEndpointServiceAdls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EndpointServiceAdl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(endpointserviceadlsResource, c.ns, name, pt, data, subresources...), &v1alpha1.EndpointServiceAdl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EndpointServiceAdl), err
}
