/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/custom/v1alpha1"
	scheme "kubeform.dev/provider-mongodbatlas-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DbRolesGetter has a method to return a DbRoleInterface.
// A group's client should implement this interface.
type DbRolesGetter interface {
	DbRoles(namespace string) DbRoleInterface
}

// DbRoleInterface has methods to work with DbRole resources.
type DbRoleInterface interface {
	Create(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.CreateOptions) (*v1alpha1.DbRole, error)
	Update(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.UpdateOptions) (*v1alpha1.DbRole, error)
	UpdateStatus(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.UpdateOptions) (*v1alpha1.DbRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DbRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DbRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DbRole, err error)
	DbRoleExpansion
}

// dbRoles implements DbRoleInterface
type dbRoles struct {
	client rest.Interface
	ns     string
}

// newDbRoles returns a DbRoles
func newDbRoles(c *CustomV1alpha1Client, namespace string) *dbRoles {
	return &dbRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dbRole, and returns the corresponding dbRole object, and an error if there is any.
func (c *dbRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DbRole, err error) {
	result = &v1alpha1.DbRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dbroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DbRoles that match those selectors.
func (c *dbRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DbRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DbRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dbroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dbRoles.
func (c *dbRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dbroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dbRole and creates it.  Returns the server's representation of the dbRole, and an error, if there is any.
func (c *dbRoles) Create(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.CreateOptions) (result *v1alpha1.DbRole, err error) {
	result = &v1alpha1.DbRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dbroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dbRole).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dbRole and updates it. Returns the server's representation of the dbRole, and an error, if there is any.
func (c *dbRoles) Update(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.UpdateOptions) (result *v1alpha1.DbRole, err error) {
	result = &v1alpha1.DbRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dbroles").
		Name(dbRole.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dbRole).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dbRoles) UpdateStatus(ctx context.Context, dbRole *v1alpha1.DbRole, opts v1.UpdateOptions) (result *v1alpha1.DbRole, err error) {
	result = &v1alpha1.DbRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dbroles").
		Name(dbRole.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dbRole).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dbRole and deletes it. Returns an error if one occurs.
func (c *dbRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dbroles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dbRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dbroles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dbRole.
func (c *dbRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DbRole, err error) {
	result = &v1alpha1.DbRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dbroles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
