/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/third/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePartyIntegrations implements PartyIntegrationInterface
type FakePartyIntegrations struct {
	Fake *FakeThirdV1alpha1
	ns   string
}

var partyintegrationsResource = schema.GroupVersionResource{Group: "third.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "partyintegrations"}

var partyintegrationsKind = schema.GroupVersionKind{Group: "third.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "PartyIntegration"}

// Get takes name of the partyIntegration, and returns the corresponding partyIntegration object, and an error if there is any.
func (c *FakePartyIntegrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PartyIntegration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(partyintegrationsResource, c.ns, name), &v1alpha1.PartyIntegration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartyIntegration), err
}

// List takes label and field selectors, and returns the list of PartyIntegrations that match those selectors.
func (c *FakePartyIntegrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PartyIntegrationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(partyintegrationsResource, partyintegrationsKind, c.ns, opts), &v1alpha1.PartyIntegrationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PartyIntegrationList{ListMeta: obj.(*v1alpha1.PartyIntegrationList).ListMeta}
	for _, item := range obj.(*v1alpha1.PartyIntegrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested partyIntegrations.
func (c *FakePartyIntegrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(partyintegrationsResource, c.ns, opts))

}

// Create takes the representation of a partyIntegration and creates it.  Returns the server's representation of the partyIntegration, and an error, if there is any.
func (c *FakePartyIntegrations) Create(ctx context.Context, partyIntegration *v1alpha1.PartyIntegration, opts v1.CreateOptions) (result *v1alpha1.PartyIntegration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(partyintegrationsResource, c.ns, partyIntegration), &v1alpha1.PartyIntegration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartyIntegration), err
}

// Update takes the representation of a partyIntegration and updates it. Returns the server's representation of the partyIntegration, and an error, if there is any.
func (c *FakePartyIntegrations) Update(ctx context.Context, partyIntegration *v1alpha1.PartyIntegration, opts v1.UpdateOptions) (result *v1alpha1.PartyIntegration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(partyintegrationsResource, c.ns, partyIntegration), &v1alpha1.PartyIntegration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartyIntegration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePartyIntegrations) UpdateStatus(ctx context.Context, partyIntegration *v1alpha1.PartyIntegration, opts v1.UpdateOptions) (*v1alpha1.PartyIntegration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(partyintegrationsResource, "status", c.ns, partyIntegration), &v1alpha1.PartyIntegration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartyIntegration), err
}

// Delete takes name of the partyIntegration and deletes it. Returns an error if one occurs.
func (c *FakePartyIntegrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(partyintegrationsResource, c.ns, name), &v1alpha1.PartyIntegration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePartyIntegrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(partyintegrationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PartyIntegrationList{})
	return err
}

// Patch applies the patch and returns the patched partyIntegration.
func (c *FakePartyIntegrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PartyIntegration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(partyintegrationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PartyIntegration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartyIntegration), err
}
