/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/teams/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTeamses implements TeamsInterface
type FakeTeamses struct {
	Fake *FakeTeamsV1alpha1
	ns   string
}

var teamsesResource = schema.GroupVersionResource{Group: "teams.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "teamses"}

var teamsesKind = schema.GroupVersionKind{Group: "teams.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "Teams"}

// Get takes name of the teams, and returns the corresponding teams object, and an error if there is any.
func (c *FakeTeamses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Teams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(teamsesResource, c.ns, name), &v1alpha1.Teams{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teams), err
}

// List takes label and field selectors, and returns the list of Teamses that match those selectors.
func (c *FakeTeamses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TeamsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(teamsesResource, teamsesKind, c.ns, opts), &v1alpha1.TeamsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TeamsList{ListMeta: obj.(*v1alpha1.TeamsList).ListMeta}
	for _, item := range obj.(*v1alpha1.TeamsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested teamses.
func (c *FakeTeamses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(teamsesResource, c.ns, opts))

}

// Create takes the representation of a teams and creates it.  Returns the server's representation of the teams, and an error, if there is any.
func (c *FakeTeamses) Create(ctx context.Context, teams *v1alpha1.Teams, opts v1.CreateOptions) (result *v1alpha1.Teams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(teamsesResource, c.ns, teams), &v1alpha1.Teams{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teams), err
}

// Update takes the representation of a teams and updates it. Returns the server's representation of the teams, and an error, if there is any.
func (c *FakeTeamses) Update(ctx context.Context, teams *v1alpha1.Teams, opts v1.UpdateOptions) (result *v1alpha1.Teams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(teamsesResource, c.ns, teams), &v1alpha1.Teams{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teams), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTeamses) UpdateStatus(ctx context.Context, teams *v1alpha1.Teams, opts v1.UpdateOptions) (*v1alpha1.Teams, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(teamsesResource, "status", c.ns, teams), &v1alpha1.Teams{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teams), err
}

// Delete takes name of the teams and deletes it. Returns an error if one occurs.
func (c *FakeTeamses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(teamsesResource, c.ns, name), &v1alpha1.Teams{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTeamses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(teamsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TeamsList{})
	return err
}

// Patch applies the patch and returns the patched teams.
func (c *FakeTeamses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Teams, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(teamsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Teams{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teams), err
}
