/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/search/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIndexes implements IndexInterface
type FakeIndexes struct {
	Fake *FakeSearchV1alpha1
	ns   string
}

var indexesResource = schema.GroupVersionResource{Group: "search.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "indexes"}

var indexesKind = schema.GroupVersionKind{Group: "search.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "Index"}

// Get takes name of the index, and returns the corresponding index object, and an error if there is any.
func (c *FakeIndexes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Index, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(indexesResource, c.ns, name), &v1alpha1.Index{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Index), err
}

// List takes label and field selectors, and returns the list of Indexes that match those selectors.
func (c *FakeIndexes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IndexList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(indexesResource, indexesKind, c.ns, opts), &v1alpha1.IndexList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IndexList{ListMeta: obj.(*v1alpha1.IndexList).ListMeta}
	for _, item := range obj.(*v1alpha1.IndexList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested indexes.
func (c *FakeIndexes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(indexesResource, c.ns, opts))

}

// Create takes the representation of a index and creates it.  Returns the server's representation of the index, and an error, if there is any.
func (c *FakeIndexes) Create(ctx context.Context, index *v1alpha1.Index, opts v1.CreateOptions) (result *v1alpha1.Index, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(indexesResource, c.ns, index), &v1alpha1.Index{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Index), err
}

// Update takes the representation of a index and updates it. Returns the server's representation of the index, and an error, if there is any.
func (c *FakeIndexes) Update(ctx context.Context, index *v1alpha1.Index, opts v1.UpdateOptions) (result *v1alpha1.Index, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(indexesResource, c.ns, index), &v1alpha1.Index{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Index), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIndexes) UpdateStatus(ctx context.Context, index *v1alpha1.Index, opts v1.UpdateOptions) (*v1alpha1.Index, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(indexesResource, "status", c.ns, index), &v1alpha1.Index{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Index), err
}

// Delete takes name of the index and deletes it. Returns an error if one occurs.
func (c *FakeIndexes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(indexesResource, c.ns, name), &v1alpha1.Index{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIndexes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(indexesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IndexList{})
	return err
}

// Patch applies the patch and returns the patched index.
func (c *FakeIndexes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Index, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(indexesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Index{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Index), err
}
