/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderAccessSetups implements ProviderAccessSetupInterface
type FakeProviderAccessSetups struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var provideraccesssetupsResource = schema.GroupVersionResource{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "provideraccesssetups"}

var provideraccesssetupsKind = schema.GroupVersionKind{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "ProviderAccessSetup"}

// Get takes name of the providerAccessSetup, and returns the corresponding providerAccessSetup object, and an error if there is any.
func (c *FakeProviderAccessSetups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProviderAccessSetup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(provideraccesssetupsResource, c.ns, name), &v1alpha1.ProviderAccessSetup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccessSetup), err
}

// List takes label and field selectors, and returns the list of ProviderAccessSetups that match those selectors.
func (c *FakeProviderAccessSetups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProviderAccessSetupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(provideraccesssetupsResource, provideraccesssetupsKind, c.ns, opts), &v1alpha1.ProviderAccessSetupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProviderAccessSetupList{ListMeta: obj.(*v1alpha1.ProviderAccessSetupList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProviderAccessSetupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerAccessSetups.
func (c *FakeProviderAccessSetups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(provideraccesssetupsResource, c.ns, opts))

}

// Create takes the representation of a providerAccessSetup and creates it.  Returns the server's representation of the providerAccessSetup, and an error, if there is any.
func (c *FakeProviderAccessSetups) Create(ctx context.Context, providerAccessSetup *v1alpha1.ProviderAccessSetup, opts v1.CreateOptions) (result *v1alpha1.ProviderAccessSetup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(provideraccesssetupsResource, c.ns, providerAccessSetup), &v1alpha1.ProviderAccessSetup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccessSetup), err
}

// Update takes the representation of a providerAccessSetup and updates it. Returns the server's representation of the providerAccessSetup, and an error, if there is any.
func (c *FakeProviderAccessSetups) Update(ctx context.Context, providerAccessSetup *v1alpha1.ProviderAccessSetup, opts v1.UpdateOptions) (result *v1alpha1.ProviderAccessSetup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(provideraccesssetupsResource, c.ns, providerAccessSetup), &v1alpha1.ProviderAccessSetup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccessSetup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderAccessSetups) UpdateStatus(ctx context.Context, providerAccessSetup *v1alpha1.ProviderAccessSetup, opts v1.UpdateOptions) (*v1alpha1.ProviderAccessSetup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(provideraccesssetupsResource, "status", c.ns, providerAccessSetup), &v1alpha1.ProviderAccessSetup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccessSetup), err
}

// Delete takes name of the providerAccessSetup and deletes it. Returns an error if one occurs.
func (c *FakeProviderAccessSetups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(provideraccesssetupsResource, c.ns, name), &v1alpha1.ProviderAccessSetup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderAccessSetups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(provideraccesssetupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProviderAccessSetupList{})
	return err
}

// Patch applies the patch and returns the patched providerAccessSetup.
func (c *FakeProviderAccessSetups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProviderAccessSetup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(provideraccesssetupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProviderAccessSetup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccessSetup), err
}
