/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupSnapshots implements BackupSnapshotInterface
type FakeBackupSnapshots struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var backupsnapshotsResource = schema.GroupVersionResource{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "backupsnapshots"}

var backupsnapshotsKind = schema.GroupVersionKind{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "BackupSnapshot"}

// Get takes name of the backupSnapshot, and returns the corresponding backupSnapshot object, and an error if there is any.
func (c *FakeBackupSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BackupSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backupsnapshotsResource, c.ns, name), &v1alpha1.BackupSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupSnapshot), err
}

// List takes label and field selectors, and returns the list of BackupSnapshots that match those selectors.
func (c *FakeBackupSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BackupSnapshotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backupsnapshotsResource, backupsnapshotsKind, c.ns, opts), &v1alpha1.BackupSnapshotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackupSnapshotList{ListMeta: obj.(*v1alpha1.BackupSnapshotList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackupSnapshotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupSnapshots.
func (c *FakeBackupSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backupsnapshotsResource, c.ns, opts))

}

// Create takes the representation of a backupSnapshot and creates it.  Returns the server's representation of the backupSnapshot, and an error, if there is any.
func (c *FakeBackupSnapshots) Create(ctx context.Context, backupSnapshot *v1alpha1.BackupSnapshot, opts v1.CreateOptions) (result *v1alpha1.BackupSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backupsnapshotsResource, c.ns, backupSnapshot), &v1alpha1.BackupSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupSnapshot), err
}

// Update takes the representation of a backupSnapshot and updates it. Returns the server's representation of the backupSnapshot, and an error, if there is any.
func (c *FakeBackupSnapshots) Update(ctx context.Context, backupSnapshot *v1alpha1.BackupSnapshot, opts v1.UpdateOptions) (result *v1alpha1.BackupSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backupsnapshotsResource, c.ns, backupSnapshot), &v1alpha1.BackupSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupSnapshot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupSnapshots) UpdateStatus(ctx context.Context, backupSnapshot *v1alpha1.BackupSnapshot, opts v1.UpdateOptions) (*v1alpha1.BackupSnapshot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backupsnapshotsResource, "status", c.ns, backupSnapshot), &v1alpha1.BackupSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupSnapshot), err
}

// Delete takes name of the backupSnapshot and deletes it. Returns an error if one occurs.
func (c *FakeBackupSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backupsnapshotsResource, c.ns, name), &v1alpha1.BackupSnapshot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backupsnapshotsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackupSnapshotList{})
	return err
}

// Patch applies the patch and returns the patched backupSnapshot.
func (c *FakeBackupSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackupSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backupsnapshotsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BackupSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupSnapshot), err
}
