/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderAccesses implements ProviderAccessInterface
type FakeProviderAccesses struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var provideraccessesResource = schema.GroupVersionResource{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "provideraccesses"}

var provideraccessesKind = schema.GroupVersionKind{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "ProviderAccess"}

// Get takes name of the providerAccess, and returns the corresponding providerAccess object, and an error if there is any.
func (c *FakeProviderAccesses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProviderAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(provideraccessesResource, c.ns, name), &v1alpha1.ProviderAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccess), err
}

// List takes label and field selectors, and returns the list of ProviderAccesses that match those selectors.
func (c *FakeProviderAccesses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProviderAccessList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(provideraccessesResource, provideraccessesKind, c.ns, opts), &v1alpha1.ProviderAccessList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProviderAccessList{ListMeta: obj.(*v1alpha1.ProviderAccessList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProviderAccessList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerAccesses.
func (c *FakeProviderAccesses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(provideraccessesResource, c.ns, opts))

}

// Create takes the representation of a providerAccess and creates it.  Returns the server's representation of the providerAccess, and an error, if there is any.
func (c *FakeProviderAccesses) Create(ctx context.Context, providerAccess *v1alpha1.ProviderAccess, opts v1.CreateOptions) (result *v1alpha1.ProviderAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(provideraccessesResource, c.ns, providerAccess), &v1alpha1.ProviderAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccess), err
}

// Update takes the representation of a providerAccess and updates it. Returns the server's representation of the providerAccess, and an error, if there is any.
func (c *FakeProviderAccesses) Update(ctx context.Context, providerAccess *v1alpha1.ProviderAccess, opts v1.UpdateOptions) (result *v1alpha1.ProviderAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(provideraccessesResource, c.ns, providerAccess), &v1alpha1.ProviderAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccess), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderAccesses) UpdateStatus(ctx context.Context, providerAccess *v1alpha1.ProviderAccess, opts v1.UpdateOptions) (*v1alpha1.ProviderAccess, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(provideraccessesResource, "status", c.ns, providerAccess), &v1alpha1.ProviderAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccess), err
}

// Delete takes name of the providerAccess and deletes it. Returns an error if one occurs.
func (c *FakeProviderAccesses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(provideraccessesResource, c.ns, name), &v1alpha1.ProviderAccess{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderAccesses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(provideraccessesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProviderAccessList{})
	return err
}

// Patch applies the patch and returns the patched providerAccess.
func (c *FakeProviderAccesses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProviderAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(provideraccessesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProviderAccess{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderAccess), err
}
