/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderSnapshotRestoreJobs implements ProviderSnapshotRestoreJobInterface
type FakeProviderSnapshotRestoreJobs struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var providersnapshotrestorejobsResource = schema.GroupVersionResource{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "providersnapshotrestorejobs"}

var providersnapshotrestorejobsKind = schema.GroupVersionKind{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "ProviderSnapshotRestoreJob"}

// Get takes name of the providerSnapshotRestoreJob, and returns the corresponding providerSnapshotRestoreJob object, and an error if there is any.
func (c *FakeProviderSnapshotRestoreJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProviderSnapshotRestoreJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(providersnapshotrestorejobsResource, c.ns, name), &v1alpha1.ProviderSnapshotRestoreJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotRestoreJob), err
}

// List takes label and field selectors, and returns the list of ProviderSnapshotRestoreJobs that match those selectors.
func (c *FakeProviderSnapshotRestoreJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProviderSnapshotRestoreJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(providersnapshotrestorejobsResource, providersnapshotrestorejobsKind, c.ns, opts), &v1alpha1.ProviderSnapshotRestoreJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProviderSnapshotRestoreJobList{ListMeta: obj.(*v1alpha1.ProviderSnapshotRestoreJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProviderSnapshotRestoreJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerSnapshotRestoreJobs.
func (c *FakeProviderSnapshotRestoreJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(providersnapshotrestorejobsResource, c.ns, opts))

}

// Create takes the representation of a providerSnapshotRestoreJob and creates it.  Returns the server's representation of the providerSnapshotRestoreJob, and an error, if there is any.
func (c *FakeProviderSnapshotRestoreJobs) Create(ctx context.Context, providerSnapshotRestoreJob *v1alpha1.ProviderSnapshotRestoreJob, opts v1.CreateOptions) (result *v1alpha1.ProviderSnapshotRestoreJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(providersnapshotrestorejobsResource, c.ns, providerSnapshotRestoreJob), &v1alpha1.ProviderSnapshotRestoreJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotRestoreJob), err
}

// Update takes the representation of a providerSnapshotRestoreJob and updates it. Returns the server's representation of the providerSnapshotRestoreJob, and an error, if there is any.
func (c *FakeProviderSnapshotRestoreJobs) Update(ctx context.Context, providerSnapshotRestoreJob *v1alpha1.ProviderSnapshotRestoreJob, opts v1.UpdateOptions) (result *v1alpha1.ProviderSnapshotRestoreJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(providersnapshotrestorejobsResource, c.ns, providerSnapshotRestoreJob), &v1alpha1.ProviderSnapshotRestoreJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotRestoreJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderSnapshotRestoreJobs) UpdateStatus(ctx context.Context, providerSnapshotRestoreJob *v1alpha1.ProviderSnapshotRestoreJob, opts v1.UpdateOptions) (*v1alpha1.ProviderSnapshotRestoreJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(providersnapshotrestorejobsResource, "status", c.ns, providerSnapshotRestoreJob), &v1alpha1.ProviderSnapshotRestoreJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotRestoreJob), err
}

// Delete takes name of the providerSnapshotRestoreJob and deletes it. Returns an error if one occurs.
func (c *FakeProviderSnapshotRestoreJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(providersnapshotrestorejobsResource, c.ns, name), &v1alpha1.ProviderSnapshotRestoreJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderSnapshotRestoreJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(providersnapshotrestorejobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProviderSnapshotRestoreJobList{})
	return err
}

// Patch applies the patch and returns the patched providerSnapshotRestoreJob.
func (c *FakeProviderSnapshotRestoreJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProviderSnapshotRestoreJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providersnapshotrestorejobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProviderSnapshotRestoreJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotRestoreJob), err
}
