/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderSnapshots implements ProviderSnapshotInterface
type FakeProviderSnapshots struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var providersnapshotsResource = schema.GroupVersionResource{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "providersnapshots"}

var providersnapshotsKind = schema.GroupVersionKind{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "ProviderSnapshot"}

// Get takes name of the providerSnapshot, and returns the corresponding providerSnapshot object, and an error if there is any.
func (c *FakeProviderSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProviderSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(providersnapshotsResource, c.ns, name), &v1alpha1.ProviderSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshot), err
}

// List takes label and field selectors, and returns the list of ProviderSnapshots that match those selectors.
func (c *FakeProviderSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProviderSnapshotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(providersnapshotsResource, providersnapshotsKind, c.ns, opts), &v1alpha1.ProviderSnapshotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProviderSnapshotList{ListMeta: obj.(*v1alpha1.ProviderSnapshotList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProviderSnapshotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerSnapshots.
func (c *FakeProviderSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(providersnapshotsResource, c.ns, opts))

}

// Create takes the representation of a providerSnapshot and creates it.  Returns the server's representation of the providerSnapshot, and an error, if there is any.
func (c *FakeProviderSnapshots) Create(ctx context.Context, providerSnapshot *v1alpha1.ProviderSnapshot, opts v1.CreateOptions) (result *v1alpha1.ProviderSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(providersnapshotsResource, c.ns, providerSnapshot), &v1alpha1.ProviderSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshot), err
}

// Update takes the representation of a providerSnapshot and updates it. Returns the server's representation of the providerSnapshot, and an error, if there is any.
func (c *FakeProviderSnapshots) Update(ctx context.Context, providerSnapshot *v1alpha1.ProviderSnapshot, opts v1.UpdateOptions) (result *v1alpha1.ProviderSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(providersnapshotsResource, c.ns, providerSnapshot), &v1alpha1.ProviderSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderSnapshots) UpdateStatus(ctx context.Context, providerSnapshot *v1alpha1.ProviderSnapshot, opts v1.UpdateOptions) (*v1alpha1.ProviderSnapshot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(providersnapshotsResource, "status", c.ns, providerSnapshot), &v1alpha1.ProviderSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshot), err
}

// Delete takes name of the providerSnapshot and deletes it. Returns an error if one occurs.
func (c *FakeProviderSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(providersnapshotsResource, c.ns, name), &v1alpha1.ProviderSnapshot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(providersnapshotsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProviderSnapshotList{})
	return err
}

// Patch applies the patch and returns the patched providerSnapshot.
func (c *FakeProviderSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProviderSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providersnapshotsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProviderSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshot), err
}
