/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProviderSnapshotBackupPolicies implements ProviderSnapshotBackupPolicyInterface
type FakeProviderSnapshotBackupPolicies struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var providersnapshotbackuppoliciesResource = schema.GroupVersionResource{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "providersnapshotbackuppolicies"}

var providersnapshotbackuppoliciesKind = schema.GroupVersionKind{Group: "cloud.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "ProviderSnapshotBackupPolicy"}

// Get takes name of the providerSnapshotBackupPolicy, and returns the corresponding providerSnapshotBackupPolicy object, and an error if there is any.
func (c *FakeProviderSnapshotBackupPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProviderSnapshotBackupPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(providersnapshotbackuppoliciesResource, c.ns, name), &v1alpha1.ProviderSnapshotBackupPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotBackupPolicy), err
}

// List takes label and field selectors, and returns the list of ProviderSnapshotBackupPolicies that match those selectors.
func (c *FakeProviderSnapshotBackupPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProviderSnapshotBackupPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(providersnapshotbackuppoliciesResource, providersnapshotbackuppoliciesKind, c.ns, opts), &v1alpha1.ProviderSnapshotBackupPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProviderSnapshotBackupPolicyList{ListMeta: obj.(*v1alpha1.ProviderSnapshotBackupPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProviderSnapshotBackupPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested providerSnapshotBackupPolicies.
func (c *FakeProviderSnapshotBackupPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(providersnapshotbackuppoliciesResource, c.ns, opts))

}

// Create takes the representation of a providerSnapshotBackupPolicy and creates it.  Returns the server's representation of the providerSnapshotBackupPolicy, and an error, if there is any.
func (c *FakeProviderSnapshotBackupPolicies) Create(ctx context.Context, providerSnapshotBackupPolicy *v1alpha1.ProviderSnapshotBackupPolicy, opts v1.CreateOptions) (result *v1alpha1.ProviderSnapshotBackupPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(providersnapshotbackuppoliciesResource, c.ns, providerSnapshotBackupPolicy), &v1alpha1.ProviderSnapshotBackupPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotBackupPolicy), err
}

// Update takes the representation of a providerSnapshotBackupPolicy and updates it. Returns the server's representation of the providerSnapshotBackupPolicy, and an error, if there is any.
func (c *FakeProviderSnapshotBackupPolicies) Update(ctx context.Context, providerSnapshotBackupPolicy *v1alpha1.ProviderSnapshotBackupPolicy, opts v1.UpdateOptions) (result *v1alpha1.ProviderSnapshotBackupPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(providersnapshotbackuppoliciesResource, c.ns, providerSnapshotBackupPolicy), &v1alpha1.ProviderSnapshotBackupPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotBackupPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProviderSnapshotBackupPolicies) UpdateStatus(ctx context.Context, providerSnapshotBackupPolicy *v1alpha1.ProviderSnapshotBackupPolicy, opts v1.UpdateOptions) (*v1alpha1.ProviderSnapshotBackupPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(providersnapshotbackuppoliciesResource, "status", c.ns, providerSnapshotBackupPolicy), &v1alpha1.ProviderSnapshotBackupPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotBackupPolicy), err
}

// Delete takes name of the providerSnapshotBackupPolicy and deletes it. Returns an error if one occurs.
func (c *FakeProviderSnapshotBackupPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(providersnapshotbackuppoliciesResource, c.ns, name), &v1alpha1.ProviderSnapshotBackupPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProviderSnapshotBackupPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(providersnapshotbackuppoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProviderSnapshotBackupPolicyList{})
	return err
}

// Patch applies the patch and returns the patched providerSnapshotBackupPolicy.
func (c *FakeProviderSnapshotBackupPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProviderSnapshotBackupPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(providersnapshotbackuppoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProviderSnapshotBackupPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProviderSnapshotBackupPolicy), err
}
