/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/auditing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuditings implements AuditingInterface
type FakeAuditings struct {
	Fake *FakeAuditingV1alpha1
	ns   string
}

var auditingsResource = schema.GroupVersionResource{Group: "auditing.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "auditings"}

var auditingsKind = schema.GroupVersionKind{Group: "auditing.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "Auditing"}

// Get takes name of the auditing, and returns the corresponding auditing object, and an error if there is any.
func (c *FakeAuditings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Auditing, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(auditingsResource, c.ns, name), &v1alpha1.Auditing{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Auditing), err
}

// List takes label and field selectors, and returns the list of Auditings that match those selectors.
func (c *FakeAuditings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AuditingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(auditingsResource, auditingsKind, c.ns, opts), &v1alpha1.AuditingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AuditingList{ListMeta: obj.(*v1alpha1.AuditingList).ListMeta}
	for _, item := range obj.(*v1alpha1.AuditingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested auditings.
func (c *FakeAuditings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(auditingsResource, c.ns, opts))

}

// Create takes the representation of a auditing and creates it.  Returns the server's representation of the auditing, and an error, if there is any.
func (c *FakeAuditings) Create(ctx context.Context, auditing *v1alpha1.Auditing, opts v1.CreateOptions) (result *v1alpha1.Auditing, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(auditingsResource, c.ns, auditing), &v1alpha1.Auditing{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Auditing), err
}

// Update takes the representation of a auditing and updates it. Returns the server's representation of the auditing, and an error, if there is any.
func (c *FakeAuditings) Update(ctx context.Context, auditing *v1alpha1.Auditing, opts v1.UpdateOptions) (result *v1alpha1.Auditing, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(auditingsResource, c.ns, auditing), &v1alpha1.Auditing{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Auditing), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuditings) UpdateStatus(ctx context.Context, auditing *v1alpha1.Auditing, opts v1.UpdateOptions) (*v1alpha1.Auditing, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(auditingsResource, "status", c.ns, auditing), &v1alpha1.Auditing{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Auditing), err
}

// Delete takes name of the auditing and deletes it. Returns an error if one occurs.
func (c *FakeAuditings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(auditingsResource, c.ns, name), &v1alpha1.Auditing{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuditings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(auditingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AuditingList{})
	return err
}

// Patch applies the patch and returns the patched auditing.
func (c *FakeAuditings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Auditing, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(auditingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Auditing{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Auditing), err
}
