/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-mongodbatlas-api/apis/x509/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuthenticationDatabaseUsers implements AuthenticationDatabaseUserInterface
type FakeAuthenticationDatabaseUsers struct {
	Fake *FakeX509V1alpha1
	ns   string
}

var authenticationdatabaseusersResource = schema.GroupVersionResource{Group: "x509.mongodbatlas.kubeform.com", Version: "v1alpha1", Resource: "authenticationdatabaseusers"}

var authenticationdatabaseusersKind = schema.GroupVersionKind{Group: "x509.mongodbatlas.kubeform.com", Version: "v1alpha1", Kind: "AuthenticationDatabaseUser"}

// Get takes name of the authenticationDatabaseUser, and returns the corresponding authenticationDatabaseUser object, and an error if there is any.
func (c *FakeAuthenticationDatabaseUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AuthenticationDatabaseUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(authenticationdatabaseusersResource, c.ns, name), &v1alpha1.AuthenticationDatabaseUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationDatabaseUser), err
}

// List takes label and field selectors, and returns the list of AuthenticationDatabaseUsers that match those selectors.
func (c *FakeAuthenticationDatabaseUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AuthenticationDatabaseUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(authenticationdatabaseusersResource, authenticationdatabaseusersKind, c.ns, opts), &v1alpha1.AuthenticationDatabaseUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AuthenticationDatabaseUserList{ListMeta: obj.(*v1alpha1.AuthenticationDatabaseUserList).ListMeta}
	for _, item := range obj.(*v1alpha1.AuthenticationDatabaseUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested authenticationDatabaseUsers.
func (c *FakeAuthenticationDatabaseUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(authenticationdatabaseusersResource, c.ns, opts))

}

// Create takes the representation of a authenticationDatabaseUser and creates it.  Returns the server's representation of the authenticationDatabaseUser, and an error, if there is any.
func (c *FakeAuthenticationDatabaseUsers) Create(ctx context.Context, authenticationDatabaseUser *v1alpha1.AuthenticationDatabaseUser, opts v1.CreateOptions) (result *v1alpha1.AuthenticationDatabaseUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(authenticationdatabaseusersResource, c.ns, authenticationDatabaseUser), &v1alpha1.AuthenticationDatabaseUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationDatabaseUser), err
}

// Update takes the representation of a authenticationDatabaseUser and updates it. Returns the server's representation of the authenticationDatabaseUser, and an error, if there is any.
func (c *FakeAuthenticationDatabaseUsers) Update(ctx context.Context, authenticationDatabaseUser *v1alpha1.AuthenticationDatabaseUser, opts v1.UpdateOptions) (result *v1alpha1.AuthenticationDatabaseUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(authenticationdatabaseusersResource, c.ns, authenticationDatabaseUser), &v1alpha1.AuthenticationDatabaseUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationDatabaseUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuthenticationDatabaseUsers) UpdateStatus(ctx context.Context, authenticationDatabaseUser *v1alpha1.AuthenticationDatabaseUser, opts v1.UpdateOptions) (*v1alpha1.AuthenticationDatabaseUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(authenticationdatabaseusersResource, "status", c.ns, authenticationDatabaseUser), &v1alpha1.AuthenticationDatabaseUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationDatabaseUser), err
}

// Delete takes name of the authenticationDatabaseUser and deletes it. Returns an error if one occurs.
func (c *FakeAuthenticationDatabaseUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(authenticationdatabaseusersResource, c.ns, name), &v1alpha1.AuthenticationDatabaseUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuthenticationDatabaseUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(authenticationdatabaseusersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AuthenticationDatabaseUserList{})
	return err
}

// Patch applies the patch and returns the patched authenticationDatabaseUser.
func (c *FakeAuthenticationDatabaseUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AuthenticationDatabaseUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(authenticationdatabaseusersResource, c.ns, name, pt, data, subresources...), &v1alpha1.AuthenticationDatabaseUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuthenticationDatabaseUser), err
}
